version: '3'

services: 
  web:
    build: .
    tty: true
    stdin_open: true
    ports: 
      - '3000:3000'
    volumes:
      - '.:/usr/src/app'
      - 'gem_cache:/gems'
    env_file:
      - .env/development/database
      - .env/development/web
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - ELASTICSEARCH_URL=search

  webpacker:
    build: .
    command: ./bin/webpack-dev-server
    ports: 
      - 3035:3035
    volumes: 
      - '.:/usr/src/app'
      - 'gem_cache:/gems'
    env_file:
      - .env/development/database
      - .env/development/web
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
  
  sidekiq:
    build: .
    tty: true
    stdin_open: true
    command: bundle exec sidekiq
    volumes: 
      - '.:/usr/src/app'
      - 'gem_cache:/gems'
    env_file:
      - .env/development/database
      - .env/development/web

  redis:
    image: redis

  search:
    image: elasticsearch:7.5.2
    ports: 
      - '9200:9200'
      - '9300:9300'
    environment: 
      - discovery.type=single-node

  database:
    image: postgres
    ports: 
      - '5432:5432'
    env_file:
      - .env/development/database
    volumes: 
      - db_data:/var/lib/postgresql/data

volumes: 
  db_data:
  gem_cache: