version: '3'

services: 
  web:
    build: .
    tty: true
    stdin_open: true
    ports: 
      - "3000:3000"
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
      - 'gem_cache:/gems'
      # install gems from host
      - '/Users/richard/workspace/carrier-base/.:/carrier_base'
      - '/Users/richard/workspace/carrier-aramex/.:/aramex'
    env_file:
      - .env/development/database
      - .env/development/web
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=webpack_dev_server

  webpack_dev_server:
    build: .
    command: ./bin/webpack-dev-server
    ports: 
      - 3035:3035
    volumes: 
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
      - 'gem_cache:/gems'
      # install gems from host
      - '/Users/richard/workspace/carrier-base/.:/carrier_base'
      - '/Users/richard/workspace/carrier-aramex/.:/aramex'
    env_file:
      - .env/development/database
      - .env/development/web
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
  
  sidekiq:
    build: .
    tty: true
    stdin_open: true
    command: bundle exec sidekiq
    volumes: 
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
      - 'gem_cache:/gems'
      # install gems from host
      - '/Users/richard/workspace/carrier-base/.:/carrier_base'
      - '/Users/richard/workspace/carrier-aramex/.:/aramex'
    env_file:
      - .env/development/database
      - .env/development/web

  redis:
    image: redis

  database:
    image: postgres
    env_file:
      - .env/development/database
    volumes: 
      - db_data:/var/lib/postgresql/data

volumes: 
  db_data:
  gem_cache: